stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
      - data/raw/Customer_data.csv
    outs:
      - data/processed/raw_data.csv
    params:
      - data_ingestion.raw_data_path
      - data_ingestion.processed_data_path

  data_validation:
    cmd: python src/data/data_validation.py
    deps:
      - src/data/data_validation.py
      - data/processed/raw_data.csv
    outs:
      - data/processed/validated_data.csv
    params:
      - data_validation.validation_rules

  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
      - src/features/feature_engineering.py
      - data/processed/validated_data.csv
    outs:
      - data/processed/features.csv
    params:
      - feature_engineering.categorical_features
      - feature_engineering.numerical_features
      - feature_engineering.target_column

  model_training:
    cmd: python src/models/model_trainer.py
    deps:
      - src/models/model_trainer.py
      - data/processed/features.csv
    outs:
      - models/staging/model.pkl
      - reports/model_performance/training_report.json
    params:
      - model_training.model_type
      - model_training.hyperparameters
      - model_training.test_size
      - model_training.random_state

  model_evaluation:
    cmd: python src/models/model_evaluator.py
    deps:
      - src/models/model_evaluator.py
      - models/staging/model.pkl
      - data/processed/features.csv
    outs:
      - reports/model_performance/evaluation_report.json
    metrics:
      - reports/model_performance/metrics.json

plots:
  - ROC:
      template: roc
      x: fpr
      y: tpr
      title: ROC Curve
      x_label: False Positive Rate
      y_label: True Positive Rate