# Basic parameters configuration for testing
data_ingestion:
  raw_data_path: "data/raw/Customer_data.csv"
  processed_data_path: "data/processed/processed_data.csv"

feature_engineering:
  numerical_features: ["tenure", "MonthlyCharges", "TotalCharges"]
  categorical_features: ["gender", "Partner", "Dependents", "PhoneService", "MultipleLines", "InternetService", "OnlineSecurity", "OnlineBackup", "DeviceProtection", "TechSupport", "StreamingTV", "StreamingMovies", "Contract", "PaperlessBilling", "PaymentMethod"]
  target_column: "Churn"

model_training:
  model_type: "xgboost"
  test_size: 0.2
  random_state: 42

model_evaluation:
  metrics: ["accuracy", "precision", "recall", "f1_score", "roc_auc"]

monitoring:
  drift_threshold: 0.15
  alert_threshold: 0.8
